### PR TITLE
Validations for multiple iframes for reloading google document

### PR DESCRIPTION
**Pull request by itsLucario**
Doc viewer won't work if there are multiple iframes. Cause reloading works based on `iframe.src = iframe.src` and it replaces src of some other iframe.

So added validations to check whether it's updating src of document viewer iframe.

### CODE REVIEW

**Comment by Marcelh1983** [comment]
Thanks for the pull request. I just tried to solve your issue using a QueryList to retrieve the iframe I didn't like the way I retrieved the iframe anyway. Could you check if 1.2.2 works for you?

**Comment by itsLucario** [comment]
Actually I tried this approach. But for some reason it is not working with the module, I tried to debug but didn't get to know why its not working. 
That is the reason I went with alternate approach. 

Can you cross check by debugging whether QueryList is returning iframes or not?

**Comment by itsLucario** [comment]
I have fixes the issue with ViewChildren. Let me know if its good.

**Comment by Marcelh1983** [comment]
Thanks a lot @itsLucario I make a stupid mistake, thanks for fixing. 1.2.3 should work.

**Comment by itsLucario** [comment]
> Thanks a lot @itsLucario I make a stupid mistake, thanks for fixing. 1.2.3 should work.

😄

**Pull request merged**
